export type { AuditEntryInput, AuditWriter } from "./audit";
export {
  CHANNEL_ACCOUNT_STATUSES,
  type ChannelAccountCreateInput,
  type ChannelAccountItem,
  ChannelAccountLimitReachedError,
  type ChannelAccountListOptions,
  type ChannelAccountManager,
  type ChannelAccountManagerDatabase,
  ChannelAccountModuleEntitlementRequiredError,
  type ChannelAccountMutationMetadata,
  ChannelAccountNotFoundError,
  ChannelAccountOrganizationUnitNotFoundError,
  type ChannelAccountPage,
  ChannelAccountPhoneConflictError,
  type ChannelAccountStatus,
  type ChannelAccountUpdateInput,
  createChannelAccountManager,
} from "./channel-account-manager";
export {
  CONTACT_STATUSES,
  type ContactCreateInput,
  type ContactItem,
  type ContactListOptions,
  type ContactManager,
  type ContactManagerDatabase,
  type ContactMutationMetadata,
  ContactNotFoundError,
  type ContactPage,
  ContactPhoneConflictError,
  type ContactStatus,
  type ContactTransaction,
  type ContactUpdateInput,
  ContactValidationError,
  createContactManager,
} from "./contact-manager";
export {
  CONVERSATION_AUTOMATION_MODES,
  CONVERSATION_STATUSES,
  type ConversationAutomationMode,
  ConversationChannelInactiveError,
  ConversationChannelNotFoundError,
  ConversationInboundEventNotFoundError,
  type ConversationItem,
  type ConversationManager,
  type ConversationManagerDatabase,
  ConversationModuleEntitlementRequiredError,
  type ConversationRouteInput,
  ConversationSenderPhoneRequiredError,
  type ConversationStatus,
  ConversationTenantNotOperationalError,
  type ConversationTransaction,
  createConversationManager,
} from "./conversation-manager";
export {
  isLimitEntitlementKey,
  isModuleEntitlementKey,
  LIMIT_ENTITLEMENT_KEYS,
  type LimitEntitlementKey,
  MODULE_ENTITLEMENT_KEYS,
  type ModuleEntitlementKey,
} from "./entitlement-catalog";
export type {
  AuditLog,
  Contact,
  Conversation,
  DomainEventOutbox,
  Message,
  OrganizationUnit,
  OutboundMessage,
  Permission,
  Role,
  RolePermission,
  TenantEntitlement,
  UserRole,
} from "./generated/prisma/client";
export * from "./generated/prisma/enums";
export {
  createInboundEventManager,
  INBOUND_EVENT_STATUSES,
  InboundChannelInactiveError,
  InboundChannelNotFoundError,
  type InboundEventInput,
  type InboundEventManager,
  type InboundEventManagerDatabase,
  type InboundEventRecord,
  type InboundEventResult,
  type InboundEventStatus,
  InboundMessagingModuleRequiredError,
  InboundTenantNotOperationalError,
} from "./inbound-event-manager";
export {
  createInboundMessageManager,
  InboundMessageEventAlreadyProcessedError,
  InboundMessageEventNotFoundError,
  InboundMessageEventTypeUnsupportedError,
  type InboundMessageManager,
  type InboundMessageManagerDatabase,
  type InboundMessagePersistInput,
  type InboundMessagePersistResult,
} from "./inbound-message-manager";
export {
  createOrganizationUnitManager,
  ORGANIZATION_UNIT_MAX_DEPTH,
  OrganizationUnitCompanyTypeReservedError,
  type OrganizationUnitCreateInput,
  OrganizationUnitCycleError,
  OrganizationUnitDepthError,
  type OrganizationUnitItem,
  OrganizationUnitLimitReachedError,
  type OrganizationUnitManager,
  type OrganizationUnitManagerDatabase,
  type OrganizationUnitMutationMetadata,
  OrganizationUnitNotFoundError,
  OrganizationUnitParentNotFoundError,
  OrganizationUnitRootInvariantError,
  type OrganizationUnitTreePage,
  type OrganizationUnitUpdateInput,
  type OrganizationUnitUsage,
} from "./organization-unit-manager";
export {
  createOutboundMessageManager,
  OUTBOUND_MESSAGE_STATUSES,
  OutboundMessageChannelInactiveError,
  OutboundMessageChannelNotFoundError,
  type OutboundMessageContent,
  type OutboundMessageCreateInput,
  type OutboundMessageManager,
  type OutboundMessageManagerDatabase,
  type OutboundMessageRecord,
  OutboundMessageStateError,
  type OutboundMessageStatus,
  type OutboundMessageTransaction,
  type OutboundMessageType,
} from "./outbound-message-manager";
export {
  isE164PhoneNumber,
  normalizePhoneNumber,
  type PhoneNormalizationOptions,
  PhoneNumberInvalidError,
} from "./phone-utils";
export {
  TenantRbacRecordNotFoundError,
  UnknownPermissionKeyError,
} from "./rbac-data-access";
export {
  createTenantAppBootstrap,
  type TenantAppBootstrap,
  type TenantAppBootstrapDatabase,
  TenantAppBootstrapNotFoundError,
} from "./tenant-app-bootstrap";
export {
  createTenantContext,
  type TenantContext,
  type TenantId,
} from "./tenant-context";
export {
  type CustomRoleCreateData,
  createTenantDataAccess,
  type DomainEventInput,
  type OrganizationUnitCreateData,
  type OrganizationUnitRepository,
  type OrganizationUnitUpdateData,
  type RolePermissionGrantOptions,
  type TenantDataAccess,
  type TenantDataAccessDatabase,
  type TenantOutboxWriter,
  type TenantPermissionResolver,
  type TenantRolePermissionRepository,
  type TenantRoleRepository,
  TenantScopedRecordNotFoundError,
  type TenantTransactionDatabase,
  type TenantUserRoleRepository,
  type UserRoleAssignmentData,
  withTenantTransaction,
} from "./tenant-data-access";
export {
  assertTenantModuleEntitled,
  createTenantEntitlementResolver,
  effectiveTenantEntitlementWhere,
  type TemporalEntitlement,
  type TenantEntitlementReadDatabase,
  type TenantEntitlementResolver,
  type TenantEntitlementStatus,
  TenantModuleEntitlementRequiredError,
  tenantEntitlementEffective,
  tenantEntitlementStatus,
} from "./tenant-entitlements";
export {
  assertTenantOperational,
  TenantNotOperationalError,
  type TenantOperationalReadDatabase,
  tenantIsOperational,
} from "./tenant-operational";
export {
  createTenantThemeRepository,
  type TenantTheme,
  type TenantThemeDatabase,
  type TenantThemeMutationMetadata,
  TenantThemeNotFoundError,
  type TenantThemeRepository,
} from "./tenant-theme";
export {
  createUserManagementManager,
  DuplicateRoleAssignmentError,
  LastOwnerRequiredError,
  OwnerRoleReadOnlyError,
  type PermissionCatalogItem,
  type RoleManagementPage,
  type RolePermissionItem,
  RolePermissionScopeConflictError,
  type UserCreateInput,
  UserEmailConflictError,
  UserEmailInvalidError,
  type UserItem,
  UserLimitReachedError,
  type UserListOptions,
  type UserManagementManager,
  type UserManagementManagerDatabase,
  type UserManagementOptions,
  type UserMutationMetadata,
  UserNotFoundError,
  type UserPage,
  type UserRoleAssignmentInput,
  type UserRoleAssignmentItem,
  UserRoleNotFoundError,
  type UserRoleOptionItem,
  type UserScopeOptionItem,
  UserScopeUnitNotFoundError,
  type UserStatusUpdateResult,
  type UserUpdateStatusInput,
  type UserUsage,
} from "./user-management-manager";
