export {
  AI_AGENT_AUTOMATION_MODES,
  type AiAgentAutomationMode,
  type AiAgentConfigDatabase,
  DEFAULT_HUMAN_HANDOFF_KEYWORDS,
  getTenantAiAgentConfig,
  type TenantAiAgentConfigData,
  type UpsertTenantAiAgentConfigInput,
  upsertTenantAiAgentConfig,
} from "./ai-agent-config-manager";
export {
  type AiAgentDispatcherDatabase,
  type AiTurnResult,
  type ProcessAiTurnParams,
  processInboundAiTurn,
} from "./ai-agent-dispatcher";
export {
  type AddKeyToPoolInput,
  type AiGatewayDatabase,
  addKeyToPool,
  type CreateAiProviderConfigInput,
  createAiProviderConfig,
  type GetTenantAiUsageSummaryInput,
  getTenantAiUsageSummary,
  type RecordAiUsageInput,
  type ResolvedProviderAndKey,
  type ResolveProviderAndKeyInput,
  recordAiUsage,
  resolveProviderAndKey,
  type TenantAiUsageSummary,
  type UpdateKeyStatusInput,
  updateKeyStatus,
} from "./ai-gateway-manager";
export {
  type AiRoutingDatabase,
  type CreateModelRouteInput,
  type CreateVirtualAliasInput,
  createVirtualAlias,
  listTenantAliases,
  type ResolvedVirtualAlias,
  type ResolveRoutesForAliasInput,
  resolveRoutesForAlias,
  seedDefaultPlatformAliases,
  type UpdateVirtualAliasRoutesInput,
  updateVirtualAliasRoutes,
  VirtualAliasConflictError,
  type VirtualAliasListItem,
  VirtualAliasNotFoundError,
} from "./ai-routing-manager";
export {
  ASSIGNMENT_POLICIES,
  type AssignmentPolicy,
  type AssignmentPolicyEngine,
  type AssignmentPolicyEngineDatabase,
  type AssignmentPolicyOptions,
  type AssignmentPolicyResult,
  createAssignmentPolicyEngine,
  InvalidAssignmentPolicyError,
  resolveAssignmentByPolicy,
} from "./assignment-policy-engine";
export type { AuditEntryInput, AuditWriter } from "./audit";
export {
  type BusinessHoursConfig,
  type DaySchedule,
  isWithinBusinessHours,
} from "./business-hours-evaluator";
export {
  CampaignChannelAccountNotFoundError,
  type CampaignDatabase,
  CampaignNotFoundError,
  type CreateCampaignInput,
  type CreateMessageTemplateInput,
  createCampaign,
  createMessageTemplate,
  getCampaignDetail,
  type ListCampaignsInput,
  type ListMessageTemplatesInput,
  listCampaigns,
  listMessageTemplates,
  MessageTemplateNotFoundError,
  type SegmentAudienceInput,
  segmentAndPopulateAudience,
} from "./campaign-manager";
export {
  CHANNEL_ACCOUNT_STATUSES,
  type ChannelAccountCreateInput,
  type ChannelAccountItem,
  ChannelAccountLimitReachedError,
  type ChannelAccountListOptions,
  type ChannelAccountManager,
  type ChannelAccountManagerDatabase,
  ChannelAccountModuleEntitlementRequiredError,
  type ChannelAccountMutationMetadata,
  ChannelAccountNotFoundError,
  ChannelAccountOrganizationUnitNotFoundError,
  type ChannelAccountPage,
  ChannelAccountPhoneConflictError,
  type ChannelAccountStatus,
  type ChannelAccountUpdateInput,
  createChannelAccountManager,
} from "./channel-account-manager";
export {
  type ChannelConnectionFailure,
  type ChannelHealthManager,
  type ChannelHealthManagerDatabase,
  type ChannelHeartbeatMetrics,
  checkStaleChannels,
  createChannelHealthManager,
  handleChannelConnectionFailure,
  recordChannelHeartbeat,
} from "./channel-health-manager";
export {
  ChannelAlreadyConnectedError,
  type ChannelPairingConnectionDetails,
  type ChannelPairingManager,
  type ChannelPairingManagerDatabase,
  confirmChannelConnected,
  createChannelPairingManager,
  disconnectChannel,
  initiateChannelPairing,
  updateChannelQrCode,
} from "./channel-pairing-manager";
export {
  CONTACT_STATUSES,
  type ContactCreateInput,
  type ContactItem,
  type ContactListOptions,
  type ContactManager,
  type ContactManagerDatabase,
  type ContactMutationMetadata,
  ContactNotFoundError,
  type ContactPage,
  ContactPhoneConflictError,
  type ContactStatus,
  type ContactTransaction,
  type ContactUpdateInput,
  ContactValidationError,
  createContactManager,
} from "./contact-manager";
export {
  CONVERSATION_AUTOMATION_MODES,
  CONVERSATION_STATUSES,
  type ConversationAutomationMode,
  ConversationChannelInactiveError,
  ConversationChannelNotFoundError,
  ConversationInboundEventNotFoundError,
  type ConversationItem,
  type ConversationManager,
  type ConversationManagerDatabase,
  ConversationModuleEntitlementRequiredError,
  type ConversationRouteInput,
  ConversationSenderPhoneRequiredError,
  type ConversationStatus,
  ConversationTenantNotOperationalError,
  type ConversationTransaction,
  createConversationManager,
} from "./conversation-manager";
export {
  createDeliveryStatusManager,
  DELIVERY_STATUS_RANK,
  type DeliveryStatus,
  DeliveryStatusChannelMismatchError,
  DeliveryStatusEventNotFoundError,
  DeliveryStatusEventTypeUnsupportedError,
  type DeliveryStatusManager,
  type DeliveryStatusManagerDatabase,
  DeliveryStatusMessageConflictError,
  DeliveryStatusMessageNotFoundError,
  type DeliveryStatusReconcileInput,
  type DeliveryStatusReconcileResult,
  type DeliveryStatusTransaction,
  type DeliveryStatusUpdate,
} from "./delivery-status-manager";
export {
  isLimitEntitlementKey,
  isModuleEntitlementKey,
  LIMIT_ENTITLEMENT_KEYS,
  type LimitEntitlementKey,
  MODULE_ENTITLEMENT_KEYS,
  type ModuleEntitlementKey,
} from "./entitlement-catalog";
export {
  createExternalHumanMessageManager,
  ExternalHumanMessageAlreadyProcessedError,
  ExternalHumanMessageChannelMismatchError,
  ExternalHumanMessageEventNotFoundError,
  ExternalHumanMessageEventTypeUnsupportedError,
  type ExternalHumanMessageInput,
  type ExternalHumanMessageManager,
  type ExternalHumanMessageManagerDatabase,
  ExternalHumanMessageNotDetectedError,
  ExternalHumanMessageOutboundEchoRaceError,
  ExternalHumanMessageProviderIdentityConflictError,
  ExternalHumanMessageProviderMessageMismatchError,
  ExternalHumanMessageRecipientMismatchError,
  ExternalHumanMessageRecipientPhoneRequiredError,
  type ExternalHumanMessageResult,
  type ExternalHumanMessageTransaction,
} from "./external-human-message-manager";
export type {
  AuditLog,
  Contact,
  Conversation,
  DomainEventOutbox,
  Message,
  OrganizationUnit,
  OutboundMessage,
  Permission,
  Role,
  RolePermission,
  Rule,
  TenantEntitlement,
  UserRole,
} from "./generated/prisma/client";
export * from "./generated/prisma/enums";
export {
  createInactivityManager,
  type InactivityManager,
  type InactivityManagerDatabase,
  type InactivityProcessResult,
  type InactivityTimeoutOptions,
  InvalidInactivityTimeoutOptionError,
  processInactivityTimeouts,
} from "./inactivity-manager";
export {
  createInboundEventDispatcher,
  InboundEventDispatchDeferredError,
  InboundEventDispatchDeliveryStatusInvalidError,
  InboundEventDispatchEventNotFoundError,
  type InboundEventDispatcher,
  type InboundEventDispatcherDatabase,
  type InboundEventDispatchInput,
  type InboundEventDispatchResult,
} from "./inbound-event-dispatcher";
export {
  createInboundEventManager,
  INBOUND_EVENT_STATUSES,
  InboundChannelInactiveError,
  InboundChannelNotFoundError,
  type InboundEventInput,
  type InboundEventManager,
  type InboundEventManagerDatabase,
  type InboundEventRecord,
  type InboundEventResult,
  type InboundEventStatus,
  InboundMessagingModuleRequiredError,
  InboundTenantNotOperationalError,
} from "./inbound-event-manager";
export {
  createInboundMessageManager,
  InboundMessageEventAlreadyProcessedError,
  InboundMessageEventNotFoundError,
  InboundMessageEventTypeUnsupportedError,
  type InboundMessageManager,
  type InboundMessageManagerDatabase,
  type InboundMessagePersistInput,
  type InboundMessagePersistResult,
} from "./inbound-message-manager";
export {
  ActiveTenantUserNotFoundError,
  type ConversationAssignmentInput,
  ConversationMutationActorNotFoundError,
  type ConversationMutationStatus,
  createInboxMutationManager,
  type InboxMutationManager,
  type InboxMutationManagerDatabase,
  InvalidConversationAssignmentError,
  InvalidConversationStateTransitionError,
} from "./inbox-mutation-manager";
export {
  createInboxQueryManager,
  type InboxConversationDetail,
  type InboxConversationItem,
  type InboxMessageItem,
  type InboxMessageQueryOptions,
  type InboxMessageQueryResult,
  type InboxQueryManager,
  type InboxQueryManagerDatabase,
  type InboxQueryOptions,
  type InboxQueryResult,
  InboxQueryValidationError,
} from "./inbox-query-manager";
export {
  type CreateKnowledgeDocumentInput,
  createKnowledgeDocument,
  type DeleteKnowledgeDocumentInput,
  deleteKnowledgeDocument,
  type GetKnowledgeDocumentDetailInput,
  getKnowledgeDocumentDetail,
  type IndexKnowledgeDocumentInput,
  indexKnowledgeDocument,
  type KnowledgeBaseDatabase,
  type KnowledgeDocumentDetail,
  KnowledgeDocumentNotFoundError,
  type KnowledgeDocumentSummary,
  type ListKnowledgeDocumentsInput,
  listKnowledgeDocuments,
} from "./knowledge-base-manager";
export {
  type SearchKnowledgeChunksInput,
  searchKnowledgeChunks,
} from "./knowledge-search-manager";
export {
  createOrganizationUnitManager,
  ORGANIZATION_UNIT_MAX_DEPTH,
  OrganizationUnitCompanyTypeReservedError,
  type OrganizationUnitCreateInput,
  OrganizationUnitCycleError,
  OrganizationUnitDepthError,
  type OrganizationUnitItem,
  OrganizationUnitLimitReachedError,
  type OrganizationUnitManager,
  type OrganizationUnitManagerDatabase,
  type OrganizationUnitMutationMetadata,
  OrganizationUnitNotFoundError,
  OrganizationUnitParentNotFoundError,
  OrganizationUnitRootInvariantError,
  type OrganizationUnitTreePage,
  type OrganizationUnitUpdateInput,
  type OrganizationUnitUsage,
} from "./organization-unit-manager";
export {
  ConversationNotFoundError,
  ConversationNotWritableError,
  createOutboundConversationMessageManager,
  OutboundConversationMessageActorNotFoundError,
  OutboundConversationMessageIdempotencyConflictError,
  type OutboundConversationMessageInput,
  type OutboundConversationMessageManager,
  type OutboundConversationMessageManagerDatabase,
  type OutboundConversationMessageResult,
} from "./outbound-conversation-message-manager";
export {
  createOutboundEchoManager,
  OutboundEchoAlreadyProcessedError,
  OutboundEchoChannelMismatchError,
  OutboundEchoConflictError,
  OutboundEchoEventNotFoundError,
  OutboundEchoEventTypeUnsupportedError,
  type OutboundEchoManager,
  type OutboundEchoManagerDatabase,
  OutboundEchoNotMatchedError,
  OutboundEchoProviderMessageMismatchError,
  type OutboundEchoReconcileInput,
  type OutboundEchoReconcileResult,
} from "./outbound-echo-manager";
export {
  createOutboundMessageManager,
  OUTBOUND_MESSAGE_STATUSES,
  OutboundMessageChannelInactiveError,
  OutboundMessageChannelNotFoundError,
  type OutboundMessageContent,
  type OutboundMessageCreateInput,
  type OutboundMessageManager,
  type OutboundMessageManagerDatabase,
  type OutboundMessageRecord,
  OutboundMessageStateError,
  type OutboundMessageStatus,
  type OutboundMessageTransaction,
  type OutboundMessageType,
} from "./outbound-message-manager";
export {
  isE164PhoneNumber,
  normalizePhoneNumber,
  type PhoneNormalizationOptions,
  PhoneNumberInvalidError,
} from "./phone-utils";
export {
  TenantRbacRecordNotFoundError,
  UnknownPermissionKeyError,
} from "./rbac-data-access";
export {
  executeRuleActions,
  interpolateTemplate,
  RuleActionChannelInactiveError,
  RuleActionContactNotFoundError,
  RuleActionConversationNotFoundError,
  RuleActionConversationNotWritableError,
  RuleActionExecutionError,
  type RuleActionExecutorDatabase,
  RuleActionInvalidStateTransitionError,
  RuleActionOrganizationUnitNotFoundError,
  RuleActionUserNotFoundError,
  type RuleExecutionContext,
  type RuleExecutionResult,
} from "./rule-action-executor";
export {
  type CreateRuleInput,
  createRuleCatalogManager,
  RULE_ACTION_TYPES,
  RULE_CONDITION_OPERATORS,
  RULE_EXECUTION_MODES,
  RULE_STATUSES,
  RULE_TRIGGER_TYPES,
  type RuleAction,
  type RuleActionType,
  type RuleCatalogManager,
  type RuleCatalogManagerDatabase,
  type RuleCatalogTransaction,
  RuleChannelAccountNotFoundError,
  type RuleCondition,
  type RuleConditionOperator,
  type RuleExecutionMode,
  type RuleItem,
  type RuleListOptions,
  type RuleMutationMetadata,
  RuleNotFoundError,
  RuleOrganizationUnitNotFoundError,
  type RuleStatus,
  type RuleTriggerType,
  RuleValidationError,
  type UpdateRuleInput,
  validateActions,
  validateConditions,
} from "./rule-catalog-manager";
export {
  evaluateRuleConditions,
  isRuleInCooldown,
  MAX_REGEX_INPUT_LENGTH,
  MAX_REGEX_PATTERN_LENGTH,
  RULE_OPERATORS,
  type RuleConditionGroup,
  type RuleEvaluationContext,
  type RuleOperator,
  resolveContextPath,
} from "./rule-condition-evaluator";
export {
  dispatchRuleTriggers,
  type RuleTriggerDispatcherDatabase,
  type RuleTriggerDispatchResult,
} from "./rule-trigger-dispatcher";
export {
  createTakeoverManager,
  InvalidConversationAutomationModeError,
  setConversationAutomationMode,
  type TakeoverManager,
  type TakeoverManagerDatabase,
} from "./takeover-manager";
export {
  extractTemplateVariables,
  renderTemplate,
} from "./template-renderer";
export {
  createTenantAppBootstrap,
  type TenantAppBootstrap,
  type TenantAppBootstrapDatabase,
  TenantAppBootstrapNotFoundError,
} from "./tenant-app-bootstrap";
export {
  createTenantContext,
  type TenantContext,
  type TenantId,
} from "./tenant-context";
export {
  type CustomRoleCreateData,
  createTenantDataAccess,
  type DomainEventInput,
  type OrganizationUnitCreateData,
  type OrganizationUnitRepository,
  type OrganizationUnitUpdateData,
  type RolePermissionGrantOptions,
  type TenantDataAccess,
  type TenantDataAccessDatabase,
  type TenantOutboxWriter,
  type TenantPermissionResolver,
  type TenantRolePermissionRepository,
  type TenantRoleRepository,
  TenantScopedRecordNotFoundError,
  type TenantTransactionDatabase,
  type TenantUserRoleRepository,
  type UserRoleAssignmentData,
  withTenantTransaction,
} from "./tenant-data-access";
export {
  assertTenantModuleEntitled,
  createTenantEntitlementResolver,
  effectiveTenantEntitlementWhere,
  type TemporalEntitlement,
  type TenantEntitlementReadDatabase,
  type TenantEntitlementResolver,
  type TenantEntitlementStatus,
  TenantModuleEntitlementRequiredError,
  tenantEntitlementEffective,
  tenantEntitlementStatus,
} from "./tenant-entitlements";
export {
  assertTenantOperational,
  TenantNotOperationalError,
  type TenantOperationalReadDatabase,
  tenantIsOperational,
} from "./tenant-operational";
export {
  createTenantThemeRepository,
  type TenantTheme,
  type TenantThemeDatabase,
  type TenantThemeMutationMetadata,
  TenantThemeNotFoundError,
  type TenantThemeRepository,
} from "./tenant-theme";
export {
  createUserManagementManager,
  DuplicateRoleAssignmentError,
  LastOwnerRequiredError,
  OwnerRoleReadOnlyError,
  type PermissionCatalogItem,
  type RoleManagementPage,
  type RolePermissionItem,
  RolePermissionScopeConflictError,
  type UserCreateInput,
  UserEmailConflictError,
  UserEmailInvalidError,
  type UserItem,
  UserLimitReachedError,
  type UserListOptions,
  type UserManagementManager,
  type UserManagementManagerDatabase,
  type UserManagementOptions,
  type UserMutationMetadata,
  UserNotFoundError,
  type UserPage,
  type UserRoleAssignmentInput,
  type UserRoleAssignmentItem,
  UserRoleNotFoundError,
  type UserRoleOptionItem,
  type UserScopeOptionItem,
  UserScopeUnitNotFoundError,
  type UserStatusUpdateResult,
  type UserUpdateStatusInput,
  type UserUsage,
} from "./user-management-manager";
